--
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: mariadb
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      database: true 
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mariadb-app
  namespace: mariadb
  labels:
    app: mariadb-app
  annotations:
    apps.open-cluster-management.io/github-path: mariadb-resources
spec:
  channel: mariadb/mariadb-app
